### ISSUE TITLE
Send Mail

### ISSUE THREAD

**Issue by LeoColomb** [Inspire-Telecom/site#2]
Mettre en place un script pour envoyer un mail à partir du formulaire.
Via https://developers.google.com/gmail/api/guides/ ?

@Tommy228 Tu peux t'en charger ?

**Comment by Tommy228** [comment]
Ça marche, je regarde ça ce week-end!

**Comment by LeoColomb** [comment]
@Tommy228 Des nouvelles ?

**Comment by Tommy228** [comment]
J'ai pu tester en javascript sur mon compte personnel, reste à mettre ça sur le site. Par contre, on ne devrait pas utiliser mon compte pour activer l'API et envoyer les mails. On en crée un spécifiquement pour envoyer les mails du site? Ce n'est pas top mais je ne vois pas une autre solution.

**Comment by LeoColomb** [comment]
Non crée un projet Google API avec ton compte Inspire. Les droits seront normalement manipulables au niveau organisation.

**Comment by Tommy228** [comment]
Bien, c'est fait. Désolé si ça me prend un peu de temps, je m'y remets très bientôt après avoir finis les partiels.

**Comment by LeoColomb** [comment]
OK. Pas de souci.

**Comment by LeoColomb** [comment]
@Tommy228 Des nouvelles ? 🛩 😸

**Comment by Tommy228** [comment]
@LeoColomb je t'en ai parlé sur hangouts, je ne sais pas si tu as lu.
